# Generated by Django 2.0 on 2019-09-11 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 20, 7, 56, 549235, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
