# Generated by Django 2.0 on 2019-09-12 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190911_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 44, 32, 332132, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
