# Generated by Django 2.0 on 2019-09-17 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190912_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 6, 48, 58, 507823, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
